apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: yarn-exporter
  name: yarn-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - name: https
      port: 9877
      targetPort: https
  selector:
    app: yarn-exporter
