apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: yarn-exporter
  name: yarn-exporter
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yarn-exporter
  template:
    metadata:
      labels:
        app: yarn-exporter
    spec:
      containers:
        - args:
            - --resource-manager.address=hadoop01:8088
            - --collect.finish-time-limit=60
            - --web.listen-address=127.0.0.1:9877
          name: yarn-exporter
          image: registry.cn-hangzhou.aliyuncs.com/clab-docker/yarn_exporter:v0.0.2
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 50m
              memory: 100Mi
            requests:
              cpu: 20m
              memory: 30Mi
        - args:
            - --logtostderr
            - --secure-listen-address=$(IP):9877
            - --tls-cipher-suites=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256
            - --upstream=http://127.0.0.1:9877/
          env:
            - name: IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          image: registry.cn-hangzhou.aliyuncs.com/clab-docker/kube-rbac-proxy:v0.4.1
          imagePullPolicy: IfNotPresent
          name: kube-rbac-proxy
          ports:
            - containerPort: 9877
              hostPort: 9877
              name: https
          resources:
            limits:
              cpu: 20m
              memory: 40Mi
            requests:
              cpu: 10m
              memory: 20Mi
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        fsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
      serviceAccountName: yarn-exporter
      tolerations:
        - operator: Exists
