{
 "title": "JMX",
 "description": "Some Information obtained from JMX exporter",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(jmx_exporter_build_info, namespace)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(jmx_exporter_build_info{namespace=\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(jmx_exporter_build_info{namespace=\"$namespace\", service=\"$service\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "{{ area }}"
    },
    {
     "expr": "jvm_memory_bytes_max{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\", area=\"heap\"}",
     "legendFormat": "max heap"
    }
   ]
  },
  {
   "title": "JVM Memory Pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "GC Occurring",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}[1m])",
     "legendFormat": "count - {{ gc }}"
    },
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}[1m])",
     "legendFormat": "time - {{ gc }}"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_deadlocked{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "deadlocked"
    },
    {
     "expr": "jvm_threads_peak{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "peak"
    }
   ]
  },
  {
   "title": "Process CPU & Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}[1m]) * 100",
     "legendFormat": "CPU"
    },
    {
     "expr": "process_resident_memory_bytes{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "Memory (RSS)"
    }
   ]
  },
  {
   "title": "JVM Runtime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "jvm_info{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "{{ vendor }}<br/><br/>{{runtime}}"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 13 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "jvm_info{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Producer Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_topic_metrics_record_send_rate{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "{{ topic }}"
      }
     ]
    },
    {
     "title": "Kafka Total Produced During Current Time Range",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 2 },
     "targets": [
      {
       "expr": "increase(kafka_producer_producer_topic_metrics_record_send_total{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}[$__range]) > 0",
       "legendFormat": "{{ topic }}"
      }
     ]
    },
    {
     "title": "Kafka Consumer Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\", topic!=\"\"}) by (namespace, service, topic)",
       "legendFormat": "{{ topic }}"
      }
     ]
    },
    {
     "title": "Kafka Total Consumed During Current Time Range",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 9 },
     "targets": [
      {
       "expr": "sum(increase(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_total{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\", topic!=\"\"}[$__range])) by (namespace, service, topic) > 0",
       "legendFormat": "{{ topic }}"
      }
     ]
    }
   ]
  }
 ]
}