{
 "title": "Kafka",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,3m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "job", "label": "Job", "query": "kafka-jmx-exporter" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kafka_brokers, kafka_cluster_name)"
   },
   {
    "name": "instance",
    "label": "Broker",
    "query": "label_values(jvm_gc_collection_seconds_count{job=\"$job\"}, instance)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_consumergroup_current_offset{kafka_cluster_name=\"$cluster\"}, topic)"
   },
   {
    "name": "consumergroup",
    "label": "Consumer Group",
    "query": "label_values(kafka_consumergroup_current_offset{topic=~\"$topic\",kafka_cluster_name=\"$cluster\"}, consumergroup)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consume Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_consumergroup_current_offset_sum{kafka_cluster_name=\"$cluster\"}[$interval]) > 0",
     "legendFormat": "{{ topic }} ({{ consumergroup }})"
    }
   ]
  },
  {
   "title": "Consume Lag",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_lag_sum{kafka_cluster_name=\"$cluster\"} > 0",
     "legendFormat": "{{ topic }} ({{ consumergroup }})"
    }
   ]
  },
  { "title": "Consumer Group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Consumer Rate for $topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumergroup_current_offset_sum{topic=~\"$topic\",consumergroup=~\"$consumergroup\",kafka_cluster_name=\"$cluster\"}[$interval])",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Current Lag for $topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_lag_sum{topic=~\"$topic\",consumergroup=~\"$consumergroup\",kafka_cluster_name=\"$cluster\"}",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Selected Groups",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kafka_consumergroup_current_offset_sum{topic=~\"$topic\",consumergroup=~\"$consumergroup\",kafka_cluster_name=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Consumers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 26 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_members{consumergroup=~\"$consumergroup\",kafka_cluster_name=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "ETA",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag_sum{topic=~\"$topic\",consumergroup=~\"$consumergroup\",kafka_cluster_name=\"$cluster\"} / rate(kafka_consumergroup_current_offset_sum{topic=~\"$topic\",consumergroup=~\"$consumergroup\",kafka_cluster_name=\"$cluster\"}[5m])",
     "legendFormat": "{{ consumergroup }}"
    }
   ]
  },
  {
   "title": "Lag By Partition ($topic)",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 30 },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{topic=~\"$topic\",consumergroup=~\"$consumergroup\",kafka_cluster_name=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Topic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Partitions",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(kafka_cluster_Partition_Value{topic=~\"$topic\",name=\"ReplicasCount\"})"
      }
     ]
    },
    {
     "title": "Total Messages",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_log_Log_Value{topic=~\"$topic\",name=\"LogEndOffset\"}) - sum(kafka_log_Log_Value{topic=~\"$topic\",name=\"LogStartOffset\"})",
       "legendFormat": "message in {{ topic }}"
      }
     ]
    },
    {
     "title": "Total Size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_log_Log_Value{topic=~\"$topic\",name=\"Size\"})",
       "legendFormat": "size"
      }
     ]
    },
    {
     "title": "Replicas",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "min(kafka_cluster_Partition_Value{topic=~\"$topic\",name=\"ReplicasCount\"})"
      }
     ]
    },
    {
     "title": "Produce Rate for $topic",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_log_Log_Value{topic=\"$topic\",name=\"LogEndOffset\"}[$interval]))",
       "legendFormat": "produce rate (message/s)"
      }
     ]
    },
    {
     "title": "Topic-Level Requests Per Second",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 24 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_BrokerTopicMetrics_MeanRate{name=\"TotalProduceRequestsPerSec\",topic=\"$topic\"})",
       "legendFormat": "Produce - Total"
      },
      {
       "expr": "sum(kafka_server_BrokerTopicMetrics_MeanRate{name=\"TotalFetchRequestsPerSec\",topic=\"$topic\"})",
       "legendFormat": "Fetch - Total"
      },
      {
       "expr": "sum(kafka_server_BrokerTopicMetrics_MeanRate{name=\"FailedProduceRequestsPerSec\",topic=\"$topic\"})",
       "legendFormat": "Produce - Failed"
      },
      {
       "expr": "sum(kafka_server_BrokerTopicMetrics_MeanRate{name=\"FailedFetchRequestsPerSec\",topic=\"$topic\"})",
       "legendFormat": "Fetch - Failed"
      }
     ]
    }
   ]
  },
  {
   "title": "Broker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_ProcessCpuLoad{job=\"$job\",instance=~\"$instance\"} * 100"
      }
     ]
    },
    {
     "title": "System CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_SystemCpuLoad{job=\"$job\",instance=~\"$instance\"} * 100"
      }
     ]
    },
    {
     "title": "File Description Usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_open_fds{job=\"$job\",instance=~\"$instance\"} / process_max_fds{job=\"$job\",instance=~\"$instance\"} * 100"
      }
     ]
    },
    {
     "title": "Heap Usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{area=\"heap\",instance=\"$instance\",job=\"$job\"} / jvm_memory_bytes_max{area=\"heap\",instance=\"$instance\",job=\"$job\"} * 100"
      }
     ]
    },
    {
     "title": "Requests Per Sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_MeanRate{name=\"RequestsPerSec\",request=\"Produce\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ request }}"
      },
      {
       "expr": "kafka_network_RequestMetrics_MeanRate{name=\"RequestsPerSec\",request=\"FetchConsumer\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ request }}"
      },
      {
       "expr": "kafka_network_RequestMetrics_MeanRate{name=\"RequestsPerSec\",request=\"FetchFollower\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ request }}"
      }
     ]
    },
    {
     "title": "Total Time to Server Request",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 25 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_Mean{name=\"TotalTimeMs\",request=\"Produce\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ request }}"
      },
      {
       "expr": "kafka_network_RequestMetrics_Mean{name=\"TotalTimeMs\",request=\"FetchConsumer\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ request }}"
      },
      {
       "expr": "kafka_network_RequestMetrics_Mean{name=\"TotalTimeMs\",request=\"FetchFollower\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ request }}"
      }
     ]
    },
    {
     "title": "Request Queue Size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestChannel_Value{name=\"ResponseQueueSize\",instance=~\"$instance\",processor=\"\"}",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "kafka_network_RequestChannel_Value{name=\"RequestQueueSize\",instance=~\"$instance\",processor=\"\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Process Memory (RSS)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Brokers",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 40 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_brokers{kafka_cluster_name=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Topics",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 40 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kafka_topic_partitions{kafka_cluster_name=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Partitions",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 40 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_topic_partitions{kafka_cluster_name=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Consumers",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 40 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_members{kafka_cluster_name=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Consumer Groups",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 40 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kafka_consumergroup_members{kafka_cluster_name=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Partition Distribution",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 40 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_server_ReplicaManager_Value{name=\"PartitionCount\",kafka_cluster_name=\"$cluster\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC - G1 Young Generation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "none", "label": "count" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_collection_seconds_count{gc=\"G1 Young Generation\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - Count"
      },
      {
       "expr": "jvm_gc_collection_seconds_sum{gc=\"G1 Young Generation\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - Sum"
      }
     ]
    },
    {
     "title": "Memory Pool Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - {{pool}}"
      }
     ]
    }
   ]
  }
 ]
}