{
 "title": "mysql",
 "description": "Dashboard from Percona Monitoring and Management project. ",
 "tags": [
  "Percona",
  "MySQL",
  "Linux_OS"
 ],
 "time": { "from": "now-5m", "to": "now-0m" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "service",
    "label": "service",
    "query": "label_values(mysql_up, service)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "MySQL 在线时长",
   "type": "singlestat",
   "description": "**MySQL Uptime**\n\nThe amount of time since the last restart of the MySQL server process.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_uptime{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "SQL Thread Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mysql_slave_status_slave_sql_running{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "IO Thread Running",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "mysql_slave_status_slave_io_running{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "InnoDB Buffer Pool Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "mysql_global_variables_innodb_buffer_pool_size{service=\"$service\"}"
    }
   ]
  },
  {
   "title": "实时QPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(mysql_global_status_queries{service=~\"$service\"}[$interval]) or irate(mysql_global_status_queries{service=~\"$service\"}[5m])"
    }
   ]
  },
  {
   "title": "实时TPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_commands_total{command=\"commit\",service=~\"$service\"}[5m]))by(service)+sum(rate(mysql_global_status_commands_total{command=\"rollback\",service=~\"$service\"}[5m]))by(service)"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "description": "**Current QPS**\n\nBased on the queries reported by MySQL's ``SHOW STATUS`` command, it is the number of statements executed by the server within the last second. This variable includes statements executed within stored programs, unlike the Questions variable. It does not count \n``COM_PING`` or ``COM_STATISTICS`` commands.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(mysql_global_status_queries{service=\"$service\"}[$interval]) or irate(mysql_global_status_queries{service=\"$service\"}[5m])",
     "legendFormat": "qps"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(mysql_global_status_commands_total{command=\"commit\",service=~\"$service\"}[5m]))by(service)+sum(rate(mysql_global_status_commands_total{command=\"rollback\",service=~\"$service\"}[5m]))by(service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "MySQL Table Locks",
   "type": "graph",
   "description": "**Table Locks**\n\nMySQL takes a number of different locks for varying reasons. In this graph we see how many Table level locks MySQL has requested from the storage engine. In the case of InnoDB, many times the locks could actually be row locks as it only takes table level locks in a few specific cases.\n\nIt is most useful to compare Locks Immediate and Locks Waited. If Locks waited is rising, it means you have lock contention. Otherwise, Locks Immediate rising and falling is normal activity.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_table_locks_immediate{service=~\"$service\"}[$interval]) or irate(mysql_global_status_table_locks_immediate{service=~\"$service\"}[5m])",
     "legendFormat": "Table Locks Immediate"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_table_locks_waited{service=~\"$service\"}[$interval]) or irate(mysql_global_status_table_locks_waited{service=~\"$service\"}[5m])",
     "legendFormat": "Table Locks Waited"
    }
   ]
  },
  {
   "title": "MySQL 网络流量",
   "type": "graph",
   "description": "**MySQL Network Traffic**\n\nHere we can see how much network traffic is generated by MySQL. Outbound is network traffic sent from MySQL and Inbound is network traffic MySQL has received.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_received{service=\"$service\"}[$interval]) or irate(mysql_global_status_bytes_received{service=\"$service\"}[5m])",
     "legendFormat": "流入流量"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_bytes_sent{service=\"$service\"}[$interval]) or irate(mysql_global_status_bytes_sent{service=\"$service\"}[5m])",
     "legendFormat": "流出流量"
    }
   ]
  },
  {
   "title": "Mysql 连接数",
   "type": "graph",
   "description": "**Max Connections** \n\nMax Connections is the maximum permitted number of simultaneous client connections. By default, this is 151. Increasing this value increases the number of file descriptors that mysqld requires. If the required number of descriptors are not available, the server reduces the value of Max Connections.\n\nmysqld actually permits Max Connections + 1 clients to connect. The extra connection is reserved for use by accounts that have the SUPER privilege, such as root.\n\nMax Used Connections is the maximum number of connections that have been in use simultaneously since the server started.\n\nConnections is the number of connection attempts (successful or not) to the MySQL server.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_threads_running{service=\"$service\"}",
     "legendFormat": "当前运行连接数"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_variables_max_connections{service=\"$service\"}",
     "legendFormat": "系统最大连接数限"
    },
    {
     "calculatedInterval": "2m",
     "expr": "max(max_over_time(mysql_global_status_threads_connected{service=\"$service\"}[$interval])  or mysql_global_status_threads_connected{service=\"$service\"} )",
     "legendFormat": "已建立的连接"
    }
   ]
  },
  {
   "title": "MySQL 慢查询总数",
   "type": "graph",
   "description": "**MySQL Slow Queries**\n\nSlow queries are defined as queries being slower than the long_query_time setting. For example, if you have long_query_time set to 3, all queries that take longer than 3 seconds to complete will show on this graph.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_slow_queries{service=\"$service\"}[$interval]) or irate(mysql_global_status_slow_queries{service=\"$service\"}[5m])",
     "legendFormat": "慢查询"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_slow_queries{service=\"$service\"}[1m])",
     "legendFormat": "慢查询"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL Internal Memory Overview",
     "type": "graph",
     "description": "***System Memory***: Total Memory for the system.\\\n***InnoDB Buffer Pool Data***: InnoDB maintains a storage area called the buffer pool for caching data and indexes in memory.\\\n***TokuDB Cache Size***: Similar in function to the InnoDB Buffer Pool,  TokuDB will allocate 50% of the installed RAM for its own cache.\\\n***Key Buffer Size***: Index blocks for MYISAM tables are buffered and are shared by all threads. key_buffer_size is the size of the buffer used for index blocks.\\\n***Adaptive Hash Index Size***: When InnoDB notices that some index values are being accessed very frequently, it builds a hash index for them in memory on top of B-Tree indexes.\\\n ***Query Cache Size***: The query cache stores the text of a SELECT statement together with the corresponding result that was sent to the client. The query cache has huge scalability problems in that only one thread can do an operation in the query cache at the same time.\\\n***InnoDB Dictionary Size***: The data dictionary is InnoDB ‘s internal catalog of tables. InnoDB stores the data dictionary on disk, and loads entries into memory while the server is running.\\\n***InnoDB Log Buffer Size***: The MySQL InnoDB log buffer allows transactions to run without having to write the log to disk before the transactions commit.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "node_memory_MemTotal{service=~\"$service\"}",
       "legendFormat": "System Memory"
      },
      {
       "expr": "mysql_global_status_innodb_page_size{service=~\"$service\"} * on (service) mysql_global_status_buffer_pool_pages{service=~\"$service\",state=\"data\"}",
       "legendFormat": "InnoDB Buffer Pool Data"
      },
      {
       "expr": "mysql_global_variables_innodb_log_buffer_size{service=~\"$service\"}",
       "legendFormat": "InnoDB Log Buffer Size"
      },
      {
       "expr": "mysql_global_variables_innodb_additional_mem_pool_size{service=~\"$service\"}",
       "legendFormat": "InnoDB Additional Memory Pool Size"
      },
      {
       "expr": "mysql_global_status_innodb_mem_dictionary{service=~\"$service\"}",
       "legendFormat": "InnoDB Dictionary Size"
      },
      {
       "expr": "mysql_global_variables_key_buffer_size{service=~\"$service\"}",
       "legendFormat": "Key Buffer Size"
      },
      {
       "expr": "mysql_global_variables_query_cache_size{service=~\"$service\"}",
       "legendFormat": "Query Cache Size"
      },
      {
       "expr": "mysql_global_status_innodb_mem_adaptive_hash{service=~\"$service\"}",
       "legendFormat": "Adaptive Hash Index Size"
      },
      {
       "expr": "mysql_global_variables_tokudb_cache_size{service=~\"$service\"}",
       "legendFormat": "TokuDB Cache Size"
      }
     ]
    }
   ]
  },
  {
   "title": "Command, Handlers, Processes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Command Counters",
     "type": "graph",
     "description": "**Top Command Counters**\n\nThe Com_{{xxx}} statement counter variables indicate the number of times each xxx statement has been executed. There is one status variable for each type of statement. For example, Com_delete and Com_update count [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements, respectively. Com_delete_multi and Com_update_multi are similar but apply to [``DELETE``](https://dev.mysql.com/doc/refman/5.7/en/delete.html) and [``UPDATE``](https://dev.mysql.com/doc/refman/5.7/en/update.html) statements that use multiple-table syntax.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "topk(5, rate(mysql_global_status_commands_total{service=~\"$service\"}[$interval])>0) or irate(mysql_global_status_commands_total{service=~\"$service\"}[5m])>0",
       "legendFormat": "Com_{{ command }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Files and Tables",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "MySQL File Openings",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "rate(mysql_global_status_opened_files{service=~\"$service\"}[$interval]) or irate(mysql_global_status_opened_files{service=~\"$service\"}[5m])",
       "legendFormat": "Openings"
      }
     ]
    },
    {
     "title": "MySQL Open Files",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_status_open_files{service=~\"$service\"}",
       "legendFormat": "Open Files"
      },
      {
       "calculatedInterval": "2m",
       "expr": "mysql_global_variables_open_files_limit{service=~\"$service\"}",
       "legendFormat": "Open Files Limit"
      },
      {
       "expr": "mysql_global_status_innodb_num_open_files{service=~\"$service\"}",
       "legendFormat": "InnoDB Open Files"
      }
     ]
    }
   ]
  }
 ]
}