{
 "title": "RabbitMQ",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,3m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(rabbitmq_up, cluster)"
   },
   {
    "name": "exchange",
    "label": "Exchange",
    "query": "label_values(rabbitmq_exchange_messages_published_in_total{cluster=\"$cluster\"}, exchange)"
   },
   {
    "name": "queue",
    "label": "Queue",
    "query": "label_values(rabbitmq_queue_messages{queue!~\"amq.gen.*\",cluster=\"$cluster\"}, queue)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queue Rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(rabbitmq_queue_messages_published_total{queue!~\"amq.gen.*\",cluster=\"$cluster\"}[$interval]) > 0",
     "legendFormat": "{{ queue }} - published"
    },
    {
     "expr": "irate(rabbitmq_queue_messages_delivered_total{queue!~\"amq.gen.*\",cluster=\"$cluster\"}[$interval]) > 0",
     "legendFormat": "{{ queue }} - deliverd"
    }
   ]
  },
  {
   "title": "Queue Messages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rabbitmq_queue_messages_ready{queue!~\"amq.gen.*\",cluster=\"$cluster\"} > 0",
     "legendFormat": "{{ queue }} - ready"
    }
   ]
  },
  {
   "title": "Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue Rate - publish & deliver & ack",
     "type": "graph",
     "gridPos": { "h": 6, "w": 18, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "irate(rabbitmq_queue_messages_published_total{queue=~\"$queue\",cluster=\"$cluster\"}[$interval])",
       "legendFormat": "{{ queue }} - publish /s"
      },
      {
       "expr": "irate(rabbitmq_queue_messages_delivered_total{queue=~\"$queue\",cluster=\"$cluster\"}[$interval])",
       "legendFormat": "{{ queue }} - deliver /s"
      },
      {
       "expr": "irate(rabbitmq_queue_messages_ack_total{queue=~\"$queue\"}[$interval])",
       "legendFormat": "{{ queue }} - ack /s"
      }
     ]
    },
    {
     "title": "Queue Messages - ready & unack",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rabbitmq_queue_messages_ready{queue=~\"$queue\",cluster=\"$cluster\"}",
       "legendFormat": "{{ queue }} - ready"
      },
      {
       "expr": "rabbitmq_queue_messages_unacknowledged{queue=~\"$queue\",cluster=\"$cluster\"}",
       "legendFormat": "{{ queue }} - unack"
      }
     ]
    },
    {
     "title": "Queue Consumers",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 26 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "rabbitmq_queue_consumers{queue=~\"$queue\",cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Queue Consumers Utilisation",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 26 },
     "format": "percentunit",
     "valueName": "current",
     "targets": [
      {
       "expr": "rabbitmq_queue_consumer_utilisation{queue=~\"$queue\",cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Queue Messages Size Total",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rabbitmq_queue_message_bytes{queue=~\"$queue\",cluster=\"$cluster\"}",
       "legendFormat": "{{ queue }} - total"
      },
      {
       "expr": "rabbitmq_queue_message_bytes_ram{queue=~\"$queue\",cluster=\"$cluster\"}",
       "legendFormat": "{{ queue }} - in ram"
      }
     ]
    },
    {
     "title": "Queue Used Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rabbitmq_queue_memory{queue=~\"$queue\",cluster=\"$cluster\"}",
       "legendFormat": "{{ queue }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Exchange",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Exchange IN/OUT Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(rabbitmq_exchange_messages_published_in_total{exchange=~\"$exchange\",cluster=\"$cluster\"}[$interval])",
       "legendFormat": "{{ exchange }} in/s"
      },
      {
       "expr": "irate(rabbitmq_exchange_messages_published_out_total{exchange=~\"$exchange\",cluster=\"$cluster\"}[$interval])",
       "legendFormat": "{{ exchange }} out/s"
      }
     ]
    },
    {
     "title": "Exchange IN/OUT Total",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rabbitmq_exchange_messages_published_in_total{exchange=~\"$exchange\",cluster=\"$cluster\"}",
       "legendFormat": "{{ exchange }} in"
      },
      {
       "expr": "rabbitmq_exchange_messages_published_out_total{exchange=~\"$exchange\",cluster=\"$cluster\"}",
       "legendFormat": "{{ exchange }} out"
      }
     ]
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "rabbitmq_up{cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Running Nodes",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(rabbitmq_running{cluster=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Total Connections",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "rabbitmq_connections{cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Total Consumers",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "rabbitmq_consumers{cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Total Exchanges",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "rabbitmq_exchanges{cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Total Queues",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 16 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "rabbitmq_queues{cluster=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Used File Descriptions",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rabbitmq_fd_used{cluster=\"$cluster\"}",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Used Sockets",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rabbitmq_sockets_used{cluster=\"$cluster\"}",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Used Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rabbitmq_node_mem_used{cluster=\"$cluster\"}",
       "legendFormat": "{{ node }}"
      }
     ]
    },
    {
     "title": "Free Disk Space",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 22 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "rabbitmq_node_disk_free{cluster=\"$cluster\"}",
       "legendFormat": "{{ node }}"
      }
     ]
    }
   ]
  }
 ]
}