apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus-webhook-qiyeweixin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus-webhook-qiyeweixin
subjects:
  - kind: ServiceAccount
    name: prometheus-webhook-qiyeweixin
    namespace: monitoring
