apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: statping
  name: statping
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: http
      nodePort: 30800
  selector:
    app: statping
