apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: statping
  name: statping
  namespace: monitoring
spec:
  endpoints:
    - bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      interval: 15s
      scrapeTimeout: 10s
      port: http
      scheme: http
      path: /status/metrics
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: statping
