apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
    name: alicloud-disk-topology-efficiency
# CSI
provisioner: diskplugin.csi.alibabacloud.com
# Flexvolume 
# provisioner: alicloud/disk
parameters:
    type: cloud_efficiency
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
