apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv-001
  labels:
    type: local
spec:
  storageClassName: prometheus-local-storage
  capacity:
    storage: 50Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/prometheus/prometheus
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: prometheus-data
          operator: In
          values:
          - "true"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv-001
  labels:
    type: local
spec:
  storageClassName: prometheus-local-storage
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  local:
    path: /opt/prometheus/grafana
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: prometheus-data
          operator: In
          values:
          - "true"

---

kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: prometheus-local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
