apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  name: grafana-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/grafana-data
    server: 10.0.35.206 
