apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
  name: prometheus-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 50Gi
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /data/prometheus-data
    server: 10.0.35.206 
