apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: redis-exporter
  name: redis-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - name: https
      port: 9121
      targetPort: https
  selector:
    app: redis-exporter
