apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    apps.kubernetes.io/component: controller
    apps.kubernetes.io/name: prometheus-operator
    apps.kubernetes.io/version: v0.30.0
  name: prometheus-operator
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      apps.kubernetes.io/component: controller
      apps.kubernetes.io/name: prometheus-operator
  template:
    metadata:
      labels:
        apps.kubernetes.io/component: controller
        apps.kubernetes.io/name: prometheus-operator
        apps.kubernetes.io/version: v0.30.0
    spec:
      containers:
        - args:
            - --kubelet-service=kube-system/kubelet
            - --logtostderr=true
            - --config-reloader-image=registry.cn-hangzhou.aliyuncs.com/clab-docker/configmap-reload:v0.0.1
            - --prometheus-config-reloader=registry.cn-hangzhou.aliyuncs.com/clab-docker/prometheus-config-reloader:v0.30.0
          image: registry.cn-hangzhou.aliyuncs.com/clab-docker/prometheus-operator:v0.30.0
          name: prometheus-operator
          ports:
            - containerPort: 8080
              name: http
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 100m
              memory: 100Mi
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
      nodeSelector:
        beta.kubernetes.io/os: linux
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
      serviceAccountName: prometheus-operator
