apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: maxwell
  name: maxwell
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    scheme: http
    port: web
    path: /prometheus
  selector:
    matchLabels:
      app: maxwell
  namespaceSelector:
    any: true
