apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kafka-exporter
    kafka-cluster-name: cluster-1
  name: kafka-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - name: https
      port: 9308
      targetPort: https
  selector:
    app: kafka-exporter
