apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: rabbitmq-exporter
  name: rabbitmq-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - name: https
      port: 9419
      targetPort: https
  selector:
    app: rabbitmq-exporter
