apiVersion: v1
kind: Service
metadata:
  namespace: kube-system
  name: coredns-prometheus
  labels:
    k8s-app: kube-dns
spec:
  selector:
    k8s-app: kube-dns
  type: ClusterIP
  clusterIP: None
  ports:
    - name: metrics
      port: 9153
      targetPort: metrics
      protocol: TCP
