apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: kudu-exporter
  name: kudu-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - name: https
      port: 9878
      targetPort: https
  selector:
    app: kudu-exporter
