apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: mysql-exporter
  name: mysql-exporter
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - name: https
      port: 9104
      targetPort: https
  selector:
    app: mysql-exporter
