apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: reactflow
  name: reactflow
  namespace: monitoring
spec:
  endpoints:
  - interval: 30s
    scheme: http
    port: "9095"
  selector:
    matchLabels:
      app: reactflow
  namespaceSelector:
    any: true
