apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: elasticsearch-exporter
  name: elasticsearch-exporter-log
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - name: https
      port: 9114
      targetPort: https
  selector:
    app: elasticsearch-exporter-log
