apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: prometheus-webhook-dingtalk
  name: prometheus-webhook-dingtalk
  namespace: monitoring
spec:
  clusterIP: None
  ports:
    - name: https
      port: 8060
      targetPort: https
  selector:
    app: prometheus-webhook-dingtalk
