{
 "title": "Kafka",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,3m,5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "job", "label": "Job", "query": "kafka-jmx-exporter" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(kafka_brokers, kafka_cluster_name)"
   },
   {
    "name": "instance",
    "label": "Broker",
    "query": "label_values(jvm_gc_collection_seconds_count{job=\"$job\"}, instance)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(kafka_consumergroup_current_offset{kafka_cluster_name=\"$cluster\"}, topic)"
   },
   {
    "name": "consumergroup",
    "label": "Consumer Group",
    "query": "label_values(kafka_consumergroup_current_offset{topic=~\"$topic\",kafka_cluster_name=\"$cluster\"}, consumergroup)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Consume Rate",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(kafka_consumergroup_current_offset_sum{kafka_cluster_name=\"$cluster\"}[$interval]) > 0",
     "legendFormat": "{{ topic }} ({{ consumergroup }})"
    }
   ]
  },
  {
   "title": "Consume Lag",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_lag_sum{kafka_cluster_name=\"$cluster\"} > 0",
     "legendFormat": "{{ topic }} ({{ consumergroup }})"
    }
   ]
  },
  { "title": "Consumer Group", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Consumer Rate for $topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumergroup_current_offset_sum{topic=~\"$topic\",consumergroup=~\"$consumergroup\",kafka_cluster_name=\"$cluster\"}[$interval])",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Current Lag for $topic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 11, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kafka_consumergroup_lag_sum{topic=~\"$topic\",consumergroup=~\"$consumergroup\",kafka_cluster_name=\"$cluster\"}",
     "legendFormat": "{{consumergroup}}"
    }
   ]
  },
  {
   "title": "Selected Groups",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 22 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kafka_consumergroup_current_offset_sum{topic=~\"$topic\",consumergroup=~\"$consumergroup\",kafka_cluster_name=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Total Consumers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 26 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_members{consumergroup=~\"$consumergroup\",kafka_cluster_name=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "ETA",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag_sum{topic=~\"$topic\",consumergroup=~\"$consumergroup\",kafka_cluster_name=\"$cluster\"} / rate(kafka_consumergroup_current_offset_sum{topic=~\"$topic\",consumergroup=~\"$consumergroup\",kafka_cluster_name=\"$cluster\"}[5m])",
     "legendFormat": "{{ consumergroup }}"
    }
   ]
  },
  {
   "title": "Lag By Partition ($topic)",
   "type": "table",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 30 },
   "targets": [
    {
     "expr": "kafka_consumergroup_lag{topic=~\"$topic\",consumergroup=~\"$consumergroup\",kafka_cluster_name=\"$cluster\"}"
    }
   ]
  },
  {
   "title": "Topic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Partitions",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 18 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "count(kafka_cluster_Partition_Value{topic=~\"$topic\",name=\"ReplicasCount\"})"
      }
     ]
    },
    {
     "title": "Total Messages",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 18 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_log_Log_Value{topic=~\"$topic\",name=\"LogEndOffset\"}) - sum(kafka_log_Log_Value{topic=~\"$topic\",name=\"LogStartOffset\"})",
       "legendFormat": "message in {{ topic }}"
      }
     ]
    },
    {
     "title": "Total Size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_log_Log_Value{topic=~\"$topic\",name=\"Size\"})",
       "legendFormat": "size"
      }
     ]
    },
    {
     "title": "Replicas",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 24 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "min(kafka_cluster_Partition_Value{topic=~\"$topic\",name=\"ReplicasCount\"})"
      }
     ]
    },
    {
     "title": "Produce Rate for $topic",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 4, "y": 24 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(rate(kafka_log_Log_Value{topic=\"$topic\",name=\"LogEndOffset\"}[$interval]))",
       "legendFormat": "produce rate (message/s)"
      }
     ]
    },
    {
     "title": "Topic-Level Requests Per Second",
     "type": "graph",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 24 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_server_BrokerTopicMetrics_MeanRate{name=\"TotalProduceRequestsPerSec\",topic=\"$topic\"})",
       "legendFormat": "Produce - Total"
      },
      {
       "expr": "sum(kafka_server_BrokerTopicMetrics_MeanRate{name=\"TotalFetchRequestsPerSec\",topic=\"$topic\"})",
       "legendFormat": "Fetch - Total"
      },
      {
       "expr": "sum(kafka_server_BrokerTopicMetrics_MeanRate{name=\"FailedProduceRequestsPerSec\",topic=\"$topic\"})",
       "legendFormat": "Produce - Failed"
      },
      {
       "expr": "sum(kafka_server_BrokerTopicMetrics_MeanRate{name=\"FailedFetchRequestsPerSec\",topic=\"$topic\"})",
       "legendFormat": "Fetch - Failed"
      }
     ]
    }
   ]
  },
  {
   "title": "Broker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Process CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 19 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_ProcessCpuLoad{job=\"$job\",instance=~\"$instance\"} * 100"
      }
     ]
    },
    {
     "title": "System CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 19 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "java_lang_OperatingSystem_SystemCpuLoad{job=\"$job\",instance=~\"$instance\"} * 100"
      }
     ]
    },
    {
     "title": "File Description Usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 19 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_open_fds{job=\"$job\",instance=~\"$instance\"} / process_max_fds{job=\"$job\",instance=~\"$instance\"} * 100"
      }
     ]
    },
    {
     "title": "Heap Usage",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 19 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "jvm_memory_bytes_used{area=\"heap\",instance=\"$instance\",job=\"$job\"} / jvm_memory_bytes_max{area=\"heap\",instance=\"$instance\",job=\"$job\"} * 100"
      }
     ]
    },
    {
     "title": "Requests Per Sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "reqps" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_MeanRate{name=\"RequestsPerSec\",request=\"Produce\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ request }}"
      },
      {
       "expr": "kafka_network_RequestMetrics_MeanRate{name=\"RequestsPerSec\",request=\"FetchConsumer\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ request }}"
      },
      {
       "expr": "kafka_network_RequestMetrics_MeanRate{name=\"RequestsPerSec\",request=\"FetchFollower\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ request }}"
      }
     ]
    },
    {
     "title": "Total Time to Server Request",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 25 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestMetrics_Mean{name=\"TotalTimeMs\",request=\"Produce\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ request }}"
      },
      {
       "expr": "kafka_network_RequestMetrics_Mean{name=\"TotalTimeMs\",request=\"FetchConsumer\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ request }}"
      },
      {
       "expr": "kafka_network_RequestMetrics_Mean{name=\"TotalTimeMs\",request=\"FetchFollower\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - {{ request }}"
      }
     ]
    },
    {
     "title": "Request Queue Size",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 25 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_network_RequestChannel_Value{name=\"ResponseQueueSize\",instance=~\"$instance\",processor=\"\"}",
       "legendFormat": "{{ name }}"
      },
      {
       "expr": "kafka_network_RequestChannel_Value{name=\"RequestQueueSize\",instance=~\"$instance\",processor=\"\"}",
       "legendFormat": "{{ name }}"
      }
     ]
    },
    {
     "title": "Process Memory (RSS)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"$job\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Brokers",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 40 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_brokers{kafka_cluster_name=\"$cluster\"}"
      }
     ]
    },
    {
     "title": "Topics",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 40 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kafka_topic_partitions{kafka_cluster_name=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Partitions",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 40 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_topic_partitions{kafka_cluster_name=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Consumers",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 40 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kafka_consumergroup_members{kafka_cluster_name=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Consumer Groups",
     "type": "singlestat",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 40 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "count(kafka_consumergroup_members{kafka_cluster_name=\"$cluster\"})"
      }
     ]
    },
    {
     "title": "Partition Distribution",
     "type": "grafana-piechart-panel",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 40 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "kafka_server_ReplicaManager_Value{name=\"PartitionCount\",kafka_cluster_name=\"$cluster\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC - G1 Young Generation",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "yaxes": [
      { "format": "none", "label": "count" }
     ],
     "targets": [
      {
       "expr": "jvm_gc_collection_seconds_count{gc=\"G1 Young Generation\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - Count"
      },
      {
       "expr": "jvm_gc_collection_seconds_sum{gc=\"G1 Young Generation\",instance=~\"$instance\"}",
       "legendFormat": "{{ instance }} - Sum"
      }
     ]
    },
    {
     "title": "Memory Pool Used",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "jvm_memory_pool_bytes_used{instance=~\"$instance\"}",
       "legendFormat": "{{instance}} - {{pool}}"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Yarn",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name",
    "label": "Name",
    "query": "label_values(yarn_app_elapsed_time_milliseconds, name)"
   },
   {
    "name": "id",
    "label": "ID",
    "query": "label_values(yarn_app_elapsed_time_milliseconds{name=\"$name\"}, id)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "API Status",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "yarn_up" }
   ]
  },
  {
   "title": "Yarn State",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "yarn_info", "legendFormat": "{{ state }}" }
   ]
  },
  {
   "title": "Start Time",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 1 },
   "format": "dateTimeAsIso",
   "valueName": "current",
   "targets": [
    { "expr": "yarn_start_time" }
   ]
  },
  {
   "title": "Total Nodes",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "yarn_nodes_total" }
   ]
  },
  {
   "title": "Total Cores",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "yarn_virtual_cores_total" }
   ]
  },
  {
   "title": "Total Memory",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 1 },
   "format": "mbytes",
   "valueName": "current",
   "targets": [
    { "expr": "yarn_memory_total_megabytes" }
   ]
  },
  {
   "title": "Applications",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "yarn_apps", "legendFormat": "{{ status }}" }
   ]
  },
  {
   "title": "Containers",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "yarn_containers", "legendFormat": "{{ status }}" }
   ]
  },
  { "title": "Group Info - $name", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Allocated Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "mbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (yarn_app_allocated_memory_megabytes{name=\"$name\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Allocated  Virtual Cores",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (yarn_app_allocated_virtual_cores{name=\"$name\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Elapsed Time",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "max(yarn_app_elapsed_time_milliseconds{name=\"$name\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Cluster Usage Percentage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum by (name) (yarn_app_cluster_usage_percentage{name=\"$name\"})",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Application Info - $id",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Allocated Memory",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "mbytes" }
     ],
     "targets": [
      {
       "expr": "yarn_app_allocated_memory_megabytes{name=\"$name\", id=\"$id\"}",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "Allocated  Virtual Cores",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "yarn_app_allocated_virtual_cores{name=\"$name\", id=\"$id\"}",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "Elapsed Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "yarn_app_elapsed_time_milliseconds{name=\"$name\", id=\"$id\"}",
       "legendFormat": "{{ id }}"
      }
     ]
    },
    {
     "title": "Cluster Usage Percentage",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 9 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "yarn_app_cluster_usage_percentage{name=\"$name\", id=\"$id\"}",
       "legendFormat": "{{ id }}"
      }
     ]
    }
   ]
  }
 ]
}
{
 "title": "Maxwell",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(MaxwellMetrics_row_count, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Replication Lag",
   "type": "singlestat",
   "description": "The time elapsed between the database transaction commit and the time it was processed by Maxwell, in milliseconds",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "MaxwellMetrics_replication_lag{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Message Publish Age P99",
   "type": "singlestat",
   "description": "the time between an event occurring on the DB and being published to kafka, in milliseconds. Note: since MySQL timestamps are accurate to the second, this is only accurate to +/- 500ms.",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "MaxwellMetrics_message_publish_age{quantile=\"0.99\",namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Message Publish Time P99",
   "type": "singlestat",
   "description": "The time it took to send a given record to Kafka, in milliseconds",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "MaxwellMetrics_message_publish_time{quantile=\"0.99\",namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Replication Queue Time P99",
   "type": "singlestat",
   "description": "the time it took to enqueue a given binlog event for processing, in milliseconds",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 1 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "MaxwellMetrics_replication_queue_time{quantile=\"0.99\",namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Processed Rows",
   "type": "singlestat",
   "description": "A count of rows that have been processed from the binlog. note that not every row results in a message being sent to Kafka.",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "MaxwellMetrics_row_count{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Inflight Messages",
   "type": "singlestat",
   "description": "the number of messages that are currently in-flight (awaiting acknowledgement from the destination, or ahead of messages which are)\n",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "MaxwellMetrics_inflightmessages_count{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Successful Kafka Messages",
   "type": "singlestat",
   "description": "Count of messages that were successfully sent to Kafka",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "MaxwellMetrics_messages_succeeded{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Failed Kafka Messages",
   "type": "singlestat",
   "description": "Count of messages that were successfully sent to Kafka",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "MaxwellMetrics_messages_failed{namespace=\"$namespace\"}"
    }
   ]
  },
  { "title": "Graph", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Processing Rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "none", "label": "msg/s" }
   ],
   "targets": [
    {
     "expr": "rate(MaxwellMetrics_row_count{namespace=\"$namespace\"}[5m])",
     "legendFormat": "processed"
    },
    {
     "expr": "rate(MaxwellMetrics_messages_succeeded{namespace=\"$namespace\"}[5m])",
     "legendFormat": "success"
    },
    {
     "expr": "rate(MaxwellMetrics_messages_failed{namespace=\"$namespace\"}[5m])",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "graph",
   "description": "The time elapsed between the database transaction commit and the time it was processed by Maxwell, in milliseconds\n",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "MaxwellMetrics_replication_lag{namespace=\"$namespace\"}",
     "legendFormat": "lag time"
    }
   ]
  },
  {
   "title": "Inflight Messages",
   "type": "graph",
   "description": "the number of messages that are currently in-flight (awaiting acknowledgement from the destination, or ahead of messages which are)\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "none", "label": "msg" }
   ],
   "targets": [
    {
     "expr": "MaxwellMetrics_inflightmessages_count{namespace=\"$namespace\"}",
     "legendFormat": "messages"
    }
   ]
  }
 ]
}
{
 "title": "JMX",
 "description": "Some Information obtained from JMX exporter",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "label_values(jmx_exporter_build_info, namespace)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "label_values(jmx_exporter_build_info{namespace=\"$namespace\"}, service)"
   },
   {
    "name": "pod",
    "label": "Pod",
    "query": "label_values(jmx_exporter_build_info{namespace=\"$namespace\", service=\"$service\"}, pod)"
   }
  ]
 },
 "panels": [
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "JVM Heap",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "{{ area }}"
    },
    {
     "expr": "jvm_memory_bytes_max{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\", area=\"heap\"}",
     "legendFormat": "max heap"
    }
   ]
  },
  {
   "title": "JVM Memory Pool",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "{{ pool }}"
    }
   ]
  },
  {
   "title": "GC Occurring",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "increase(jvm_gc_collection_seconds_count{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}[1m])",
     "legendFormat": "count - {{ gc }}"
    },
    {
     "expr": "increase(jvm_gc_collection_seconds_sum{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}[1m])",
     "legendFormat": "time - {{ gc }}"
    }
   ]
  },
  {
   "title": "JVM Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "daemon"
    },
    {
     "expr": "jvm_threads_deadlocked{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "deadlocked"
    },
    {
     "expr": "jvm_threads_peak{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "peak"
    }
   ]
  },
  {
   "title": "Process CPU & Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_seconds_total{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}[1m]) * 100",
     "legendFormat": "CPU"
    },
    {
     "expr": "process_resident_memory_bytes{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "Memory (RSS)"
    }
   ]
  },
  {
   "title": "JVM Runtime",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 7, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "jvm_info{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "{{ vendor }}<br/><br/>{{runtime}}"
    }
   ]
  },
  {
   "title": "JVM Version",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 13 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "jvm_info{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Producer Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 2 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "kafka_producer_producer_topic_metrics_record_send_rate{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}",
       "legendFormat": "{{ topic }}"
      }
     ]
    },
    {
     "title": "Kafka Total Produced During Current Time Range",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 2 },
     "targets": [
      {
       "expr": "increase(kafka_producer_producer_topic_metrics_record_send_total{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\"}[$__range]) > 0",
       "legendFormat": "{{ topic }}"
      }
     ]
    },
    {
     "title": "Kafka Consumer Rate",
     "type": "graph",
     "gridPos": { "h": 7, "w": 14, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "sum(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_rate{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\", topic!=\"\"}) by (namespace, service, topic)",
       "legendFormat": "{{ topic }}"
      }
     ]
    },
    {
     "title": "Kafka Total Consumed During Current Time Range",
     "type": "table",
     "gridPos": { "h": 7, "w": 10, "x": 14, "y": 9 },
     "targets": [
      {
       "expr": "sum(increase(kafka_consumer_consumer_fetch_manager_metrics_records_consumed_total{namespace=\"$namespace\", service=\"$service\", pod=\"$pod\", topic!=\"\"}[$__range])) by (namespace, service, topic) > 0",
       "legendFormat": "{{ topic }}"
      }
     ]
    }
   ]
  }
 ]
}